name = "login-smaiclub-kv"
main = "src/index.js"
compatibility_date = "2025-12-14"

# 路由配置
routes = [
	{ pattern = "login.smaiclub.top", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "user_db"
database_id = "0b100581-db8c-46a3-92f8-55d2ee05c30a"